### ISSUE TITLE
Handlebars 2.0

### ISSUE THREAD

**Issue by btamas** [lasso-js/lasso-handlebars#1]
Hi,

Could you update the dependencies to handlebars 4? BTW if you just remove it, it can work also, because in this case I can use that I want.

Thanks in advance.

**Comment by patrick-steele-idem** [comment]
Hey @btamas, would you mind sending a PR to remove the `handlebars` dependency so that the application's version of `handlebars`gets picked up instead? I'll merge the change, bump the major version and then publish a new version. Thanks!

**Comment by btamas** [comment]
Hi @patrick-steele-idem,

I created that. Thanks.

**Comment by patrick-steele-idem** [comment]
Fixed by PR #2
